/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import DAO.FuncionarioDAO;
import Entidades.Funcionario;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Airton Robson
 */
public class EditFuncForm extends javax.swing.JFrame {

    /**
     * Creates new form NovoFuncForm
     */
    private final Funcionario f1;
    private final FuncionarioForm ff;
    private final int id;
    String sexo = "";
    
    public EditFuncForm(java.awt.Frame parent, boolean modal, Funcionario func, FuncionarioForm funcForm, int id) {
        initComponents();
        this.f1 = func;
        this.ff = funcForm;
        carregarCampos();
        carregarCamposEspeciais();
        definirSexo();
        this.id = id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_atestado = new javax.swing.ButtonGroup();
        bg_suspensão = new javax.swing.ButtonGroup();
        bg_advertencia = new javax.swing.ButtonGroup();
        bg_sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_funcao = new javax.swing.JTextField();
        tf_funcao_atual = new javax.swing.JTextField();
        tf_num_dependentes = new javax.swing.JTextField();
        tf_endereco = new javax.swing.JTextField();
        tf_rg = new javax.swing.JTextField();
        tf_nome_pai = new javax.swing.JTextField();
        tf_nome_mae = new javax.swing.JTextField();
        tf_pis = new javax.swing.JTextField();
        tf_ctps = new javax.swing.JTextField();
        tf_serie = new javax.swing.JTextField();
        ff_data_nasc = new javax.swing.JFormattedTextField();
        ff_telefone1 = new javax.swing.JFormattedTextField();
        ff_telefone2 = new javax.swing.JFormattedTextField();
        ff_cpf = new javax.swing.JFormattedTextField();
        ff_data_expedicao = new javax.swing.JFormattedTextField();
        ff_data_admissao = new javax.swing.JFormattedTextField();
        cb_estado_civil = new javax.swing.JComboBox();
        tf_loja_atual = new javax.swing.JTextField();
        cb_grau_intrucao = new javax.swing.JComboBox();
        cb_uniforme = new javax.swing.JComboBox();
        cb_calcado = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        rb_fem = new javax.swing.JRadioButton();
        rb_masc = new javax.swing.JRadioButton();
        jb_cadastrar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        tf_org_expeditor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), java.awt.Color.blue)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Função:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Estado Civil:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Número de dependentes:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Endereço:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Telefone 1:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Telefone 2:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("CPF:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("RG:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Nome do Pai:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Nome da Mãe:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Órgão Expeditor:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Data de Nascimento:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Grau de Instrução:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Função Atual:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("PIS:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("CTPS:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Série:");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Data de Admissão:");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Loja Atual:");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Data da Expedição:");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Calçado:");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Uniforme:");

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        tf_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nomeKeyPressed(evt);
            }
        });

        tf_funcao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_funcaoKeyPressed(evt);
            }
        });

        tf_funcao_atual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_funcao_atualKeyPressed(evt);
            }
        });

        tf_num_dependentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_num_dependentesKeyPressed(evt);
            }
        });

        tf_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_enderecoKeyPressed(evt);
            }
        });

        tf_rg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_rgKeyPressed(evt);
            }
        });

        tf_nome_pai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nome_paiKeyPressed(evt);
            }
        });

        tf_nome_mae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nome_maeKeyPressed(evt);
            }
        });

        tf_pis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pisKeyPressed(evt);
            }
        });

        tf_ctps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_ctpsKeyPressed(evt);
            }
        });

        tf_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_serieKeyPressed(evt);
            }
        });

        try {
            ff_data_nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_data_nasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ff_data_nascKeyPressed(evt);
            }
        });

        try {
            ff_telefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_telefone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ff_telefone1KeyPressed(evt);
            }
        });

        try {
            ff_telefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_telefone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ff_telefone2KeyPressed(evt);
            }
        });

        try {
            ff_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_cpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ff_cpfKeyPressed(evt);
            }
        });

        try {
            ff_data_expedicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_data_expedicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ff_data_expedicaoKeyPressed(evt);
            }
        });

        try {
            ff_data_admissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_data_admissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ff_data_admissaoKeyPressed(evt);
            }
        });

        cb_estado_civil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo" }));
        cb_estado_civil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_estado_civilKeyPressed(evt);
            }
        });

        tf_loja_atual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_loja_atualKeyPressed(evt);
            }
        });

        cb_grau_intrucao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Cursando Ensino Médio", "Ensino Médio Incompleto", "Ensino Médio Completo", "Cursando Ensino Superior", "Ensino Superior Incompleto", "Ensino Superior Completo" }));
        cb_grau_intrucao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_grau_intrucaoKeyPressed(evt);
            }
        });

        cb_uniforme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "PP", "P", "M", "G", "GG" }));
        cb_uniforme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_uniformeKeyPressed(evt);
            }
        });

        cb_calcado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45" }));
        cb_calcado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_calcadoKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setText("Sexo:");

        bg_sexo.add(rb_fem);
        rb_fem.setText("Feminino");
        rb_fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femActionPerformed(evt);
            }
        });
        rb_fem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_femKeyPressed(evt);
            }
        });

        bg_sexo.add(rb_masc);
        rb_masc.setText("Masculino");
        rb_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mascActionPerformed(evt);
            }
        });
        rb_masc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_mascKeyPressed(evt);
            }
        });

        jb_cadastrar.setText("Cadastrar");
        jb_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarActionPerformed(evt);
            }
        });
        jb_cadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_cadastrarKeyPressed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        jb_cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_cancelarKeyPressed(evt);
            }
        });

        tf_org_expeditor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_org_expeditorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_nome_pai))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_nome))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_num_dependentes))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_endereco)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_org_expeditor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nome_mae, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_data_expedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ff_data_admissao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_masc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_fem))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_funcao_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_pis, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_ctps))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(201, 201, 201))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(195, 195, 195)
                                        .addComponent(cb_calcado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_uniforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel25)
                                        .addGap(54, 54, 54)))
                                .addGap(0, 252, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jb_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_grau_intrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_loja_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ff_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_nome_pai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nome_mae, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ff_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_org_expeditor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(ff_data_expedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_num_dependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ff_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(cb_uniforme, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_calcado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ff_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cb_grau_intrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_loja_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_pis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tf_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_funcao_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_estado_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(rb_fem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_masc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(ff_data_admissao, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tf_ctps, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(374, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1019, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_org_expeditorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_org_expeditorKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_org_expeditorKeyPressed

    private void jb_cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_cancelarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_jb_cancelarKeyPressed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new FuncionarioForm().show();
        } catch (IOException ex) {
            Logger.getLogger(EditFuncForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_cadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_cadastrarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_jb_cadastrarKeyPressed

    private void jb_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarActionPerformed
        // TODO add your handling code here:
        Funcionario func = new Funcionario();

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        func.setNome(tf_nome.getText().toUpperCase());
        func.setAdmissao(ff_data_admissao.getText());
        func.setCalcado(String.valueOf(cb_calcado.getSelectedItem()));
        func.setCpf(ff_cpf.getText());
        func.setCtps(Integer.parseInt(tf_ctps.getText()));
        func.setData_expedicao(ff_data_expedicao.getText());
        func.setData_nasc(ff_data_nasc.getText());
        func.setDependentes(tf_num_dependentes.getText());
        func.setEndereco(tf_endereco.getText().toUpperCase());
        func.setEst_civil(String.valueOf(cb_estado_civil.getSelectedItem()));
        func.setFuncao(tf_funcao.getText().toUpperCase());
        func.setFuncao_atual(tf_funcao_atual.getText().toUpperCase());
        func.setGrau_instru(String.valueOf(cb_grau_intrucao.getSelectedItem()));
        func.setLoja_atual(tf_loja_atual.getText().toUpperCase());
        func.setNome_pai(tf_nome_pai.getText().toUpperCase());
        func.setNome_mae(tf_nome_mae.getText().toUpperCase());
        func.setOrg_expeditor(tf_org_expeditor.getText().toUpperCase());
        func.setPis(tf_pis.getText());
        func.setRg(tf_rg.getText());
        func.setSerie(tf_serie.getText().toUpperCase());
        func.setSexo(sexo);
        System.out.println(func.getSexo());
        func.setTelefone1(ff_telefone1.getText());
        func.setTelefone2(ff_telefone2.getText());
        func.setUniforme(String.valueOf(cb_uniforme.getSelectedItem()));
        func.setId(id);
        FuncionarioDAO dao;
        try {
            dao = new FuncionarioDAO();
            dao.editarFuncionario(func);
            dispose();
            new FuncionarioForm().show();
        } catch (SQLException ex) {
            Logger.getLogger(NovoFuncForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro", "Erro ao cadastrar funcionário!!", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(NovoFuncForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EditFuncForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_cadastrarActionPerformed

    private void rb_mascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_mascKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_rb_mascKeyPressed

    private void rb_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mascActionPerformed
        // TODO add your handling code here:
        sexo = "Masculino";
    }//GEN-LAST:event_rb_mascActionPerformed

    private void rb_femKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_femKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_rb_femKeyPressed

    private void rb_femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femActionPerformed
        // TODO add your handling code here:
        sexo = "Feminino";
    }//GEN-LAST:event_rb_femActionPerformed

    private void cb_calcadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_calcadoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_cb_calcadoKeyPressed

    private void cb_uniformeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_uniformeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_cb_uniformeKeyPressed

    private void cb_grau_intrucaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_grau_intrucaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_cb_grau_intrucaoKeyPressed

    private void tf_loja_atualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_loja_atualKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_loja_atualKeyPressed

    private void cb_estado_civilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_estado_civilKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_cb_estado_civilKeyPressed

    private void ff_data_admissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ff_data_admissaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_ff_data_admissaoKeyPressed

    private void ff_data_expedicaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ff_data_expedicaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_ff_data_expedicaoKeyPressed

    private void ff_cpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ff_cpfKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_ff_cpfKeyPressed

    private void ff_telefone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ff_telefone2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_ff_telefone2KeyPressed

    private void ff_telefone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ff_telefone1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_ff_telefone1KeyPressed

    private void ff_data_nascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ff_data_nascKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_ff_data_nascKeyPressed

    private void tf_serieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_serieKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_serieKeyPressed

    private void tf_ctpsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ctpsKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_ctpsKeyPressed

    private void tf_pisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pisKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_pisKeyPressed

    private void tf_nome_maeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nome_maeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_nome_maeKeyPressed

    private void tf_nome_paiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nome_paiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_nome_paiKeyPressed

    private void tf_rgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_rgKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_rgKeyPressed

    private void tf_enderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_enderecoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_enderecoKeyPressed

    private void tf_num_dependentesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_num_dependentesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_num_dependentesKeyPressed

    private void tf_funcao_atualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_funcao_atualKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_funcao_atualKeyPressed

    private void tf_funcaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_funcaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_funcaoKeyPressed

    private void tf_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_nomeKeyPressed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoFuncForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoFuncForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoFuncForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoFuncForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoFuncForm().setVisible(true);
            }
        });
    }
    
    private void carregarCampos(){
        
        tf_nome.setText(f1.getNome());
        ff_data_nasc.setText(f1.getData_nasc());
        tf_funcao.setText(f1.getFuncao());
        tf_ctps.setText(String.valueOf(f1.getCtps()));
        tf_endereco.setText(f1.getEndereco());
        tf_funcao_atual.setText(f1.getFuncao_atual());
        tf_loja_atual.setText(f1.getLoja_atual());
        tf_nome_mae.setText(f1.getNome_mae());
        tf_nome_pai.setText(f1.getNome_pai());
        tf_num_dependentes.setText(f1.getDependentes());
        tf_org_expeditor.setText(f1.getOrg_expeditor());
        tf_pis.setText(f1.getPis());
        tf_rg.setText(f1.getRg());
        tf_serie.setText(f1.getSerie());
        ff_telefone1.setText(f1.getTelefone1());
        ff_telefone2.setText(f1.getTelefone2());
        ff_data_admissao.setText(f1.getAdmissao());
        ff_data_expedicao.setText(f1.getData_expedicao());
        ff_cpf.setText(f1.getCpf());
        
        
        
    }
    
    public void carregarCamposEspeciais(){
        int i = 0;
        while(i < cb_grau_intrucao.getItemCount()){
            
           try{
                if(f1.getGrau_instru().equals(cb_grau_intrucao.getItemAt(i))){
                cb_grau_intrucao.setSelectedIndex(i);
                break;
                }else{
                    i++;
                }   
            }catch(Exception ex){
                    cb_grau_intrucao.setSelectedIndex(0);
                    break;
            }   
           
            
        }
        int di = 0;
        
        while(di < cb_calcado.getItemCount()){
            
            try{
                if(f1.getCalcado().equals(cb_calcado.getItemAt(di))){
                cb_calcado.setSelectedIndex(di);
                break;
            }else{
                    di++;
                }
            }catch(Exception ex){
                cb_calcado.setSelectedIndex(0);
                break;
            }
            
        }
        
        i = 0;
        while(i < cb_estado_civil.getItemCount()){
            
            try{
                if(f1.getEst_civil().equals(cb_estado_civil.getItemAt(i))){
                
                cb_estado_civil.setSelectedIndex(i);
                break;
            }
                else{
                    i++;
                }
            }catch(Exception ex){
                cb_estado_civil.setSelectedIndex(0);
                break;
            }
            
        }
        
        i = 0;
        while(i < cb_uniforme.getItemCount()){
            
            try{
                if(f1.getUniforme().equals(cb_uniforme.getItemAt(i))){
                cb_uniforme.setSelectedIndex(i);
                break;
            }else{
                    i++;
                }
            }catch(Exception ex){
                cb_uniforme.setSelectedIndex(0);
                break;
            }
            
        }
        
        if(f1.getSexo().equals("Masculino")){
            rb_masc.setSelected(true);
        }else if(f1.getSexo().equals("Feminino")){
            rb_fem.setSelected(true);
        }
        
    }
    public void definirSexo(){
        if(rb_masc.isSelected()){
            sexo = "Masculino";
            
        }else if(rb_fem.isSelected()){
            sexo = "Feminino";
        }
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_advertencia;
    private javax.swing.ButtonGroup bg_atestado;
    private javax.swing.ButtonGroup bg_sexo;
    private javax.swing.ButtonGroup bg_suspensão;
    private javax.swing.JComboBox cb_calcado;
    private javax.swing.JComboBox cb_estado_civil;
    private javax.swing.JComboBox cb_grau_intrucao;
    private javax.swing.JComboBox cb_uniforme;
    private javax.swing.JFormattedTextField ff_cpf;
    private javax.swing.JFormattedTextField ff_data_admissao;
    private javax.swing.JFormattedTextField ff_data_expedicao;
    private javax.swing.JFormattedTextField ff_data_nasc;
    private javax.swing.JFormattedTextField ff_telefone1;
    private javax.swing.JFormattedTextField ff_telefone2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_cadastrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JRadioButton rb_fem;
    private javax.swing.JRadioButton rb_masc;
    private javax.swing.JTextField tf_ctps;
    private javax.swing.JTextField tf_endereco;
    private javax.swing.JTextField tf_funcao;
    private javax.swing.JTextField tf_funcao_atual;
    private javax.swing.JTextField tf_loja_atual;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nome_mae;
    private javax.swing.JTextField tf_nome_pai;
    private javax.swing.JTextField tf_num_dependentes;
    private javax.swing.JTextField tf_org_expeditor;
    private javax.swing.JTextField tf_pis;
    private javax.swing.JTextField tf_rg;
    private javax.swing.JTextField tf_serie;
    // End of variables declaration//GEN-END:variables
}
