/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import DAO.FuncionarioDAO;
import Entidades.Funcionario;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Airton Robson
 */
public class FuncionarioForm extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioForm
     */
    List<Funcionario> minhaList = new ArrayList<Funcionario>();
    String pesq = "";
    String filtro = "TODOS";
    public FuncionarioForm() throws IOException {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_filtro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_func = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jb_novo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jb_deletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_nomePesq = new javax.swing.JTextField();
        rb_cosmos = new javax.swing.JRadioButton();
        rb_matriz = new javax.swing.JRadioButton();
        rb_filial = new javax.swing.JRadioButton();
        rb_rotisseria = new javax.swing.JRadioButton();
        rb_todos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tb_func.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_func.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_funcKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_func);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1198, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jb_novo.setText("Novo [F1]");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });
        jb_novo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_novoKeyPressed(evt);
            }
        });

        jb_editar.setText("Editar [F2]");
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });
        jb_editar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_editarKeyPressed(evt);
            }
        });

        jb_sair.setText("Sair [ESC]");
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });
        jb_sair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_sairKeyPressed(evt);
            }
        });

        jb_deletar.setText("Deletar [F3]");
        jb_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deletarActionPerformed(evt);
            }
        });
        jb_deletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_deletarKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        tf_nomePesq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_nomePesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomePesqActionPerformed(evt);
            }
        });
        tf_nomePesq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_nomePesqFocusGained(evt);
            }
        });
        tf_nomePesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nomePesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nomePesqKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nomePesqKeyTyped(evt);
            }
        });

        bg_filtro.add(rb_cosmos);
        rb_cosmos.setText("COSMOS");
        rb_cosmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cosmosActionPerformed(evt);
            }
        });

        bg_filtro.add(rb_matriz);
        rb_matriz.setText("MATRIZ");
        rb_matriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_matrizActionPerformed(evt);
            }
        });

        bg_filtro.add(rb_filial);
        rb_filial.setText("FILIAL");
        rb_filial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_filialActionPerformed(evt);
            }
        });

        bg_filtro.add(rb_rotisseria);
        rb_rotisseria.setText("ROTISSERIA");
        rb_rotisseria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_rotisseriaActionPerformed(evt);
            }
        });

        bg_filtro.add(rb_todos);
        rb_todos.setSelected(true);
        rb_todos.setText("TODOS");
        rb_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_novo)
                        .addGap(72, 72, 72)
                        .addComponent(jb_editar)
                        .addGap(70, 70, 70)
                        .addComponent(jb_deletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jb_sair)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_cosmos)
                                .addGap(44, 44, 44)
                                .addComponent(rb_matriz)
                                .addGap(54, 54, 54)
                                .addComponent(rb_filial)
                                .addGap(51, 51, 51)
                                .addComponent(rb_rotisseria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_todos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nomePesq)))
                        .addGap(92, 92, 92))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_cosmos)
                    .addComponent(rb_matriz)
                    .addComponent(rb_filial)
                    .addComponent(rb_rotisseria)
                    .addComponent(rb_todos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1254, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jb_sairActionPerformed

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        // TODO add your handling code here:
        new NovoFuncForm().show();
        dispose();
    }//GEN-LAST:event_jb_novoActionPerformed

    private void tf_nomePesqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomePesqKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomePesqKeyTyped

    private void tf_nomePesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomePesqKeyReleased
        // TODO add your handling code here:
        pesq = tf_nomePesq.getText();
        String ant = "";
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            if(pesq.equals("")){
                preencherTabela();
            }else{
              minhaList =  dao.ListPesq(pesq, filtro);
              preencherPesq(minhaList);
              ant = pesq;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!!", "Erro", JOptionPane.ERROR_MESSAGE);
            tf_nomePesq.setText(ant);
        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tf_nomePesqKeyReleased

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
        // TODO add your handling code here:
        Funcionario func = new Funcionario();
        if (tb_func.getSelectedRow() != -1) {
            
          func = (Funcionario) minhaList.get(tb_func.getSelectedRow()); 
          
          EditFuncForm dialog = new EditFuncForm(this, true, func, this, func.getId());            
          dialog.setVisible(true);
          dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_editarActionPerformed

    private void tf_nomePesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomePesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomePesqActionPerformed

    private void jb_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deletarActionPerformed
        // TODO add your handling code here:
        Funcionario func = new Funcionario();
        FuncionarioDAO dao;
        try {
            dao = new FuncionarioDAO();
        
        if (tb_func.getSelectedRow() == -1) {
           JOptionPane.showMessageDialog(null, "Selecione um registro", "Erro", JOptionPane.ERROR_MESSAGE);
           return;
       }
        
        
        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?", "confirmação", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        
            try {
                func =(Funcionario) minhaList.get(tb_func.getSelectedRow());
                dao.excluirFuncionario(func);
                tf_nomePesq.setText("");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }
         } catch (SQLException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }                      
        try { 
            preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_deletarActionPerformed

    private void jb_novoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_novoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_sairActionPerformed(null);
    }//GEN-LAST:event_jb_novoKeyPressed

    private void jb_editarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_editarKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_sairActionPerformed(null);
    }//GEN-LAST:event_jb_editarKeyPressed

    private void jb_deletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_deletarKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_sairActionPerformed(null);
    }//GEN-LAST:event_jb_deletarKeyPressed

    private void jb_sairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_sairKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_sairActionPerformed(null);
    }//GEN-LAST:event_jb_sairKeyPressed

    private void tf_nomePesqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nomePesqFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tf_nomePesqFocusGained

    private void tf_nomePesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomePesqKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_sairActionPerformed(null);
    }//GEN-LAST:event_tf_nomePesqKeyPressed

    private void tb_funcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_funcKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_sairActionPerformed(null);
    }//GEN-LAST:event_tb_funcKeyPressed

    private void rb_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_todosActionPerformed
        // TODO add your handling code here:
        filtro = "TODOS";
        try {
            preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_todosActionPerformed

    private void rb_cosmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cosmosActionPerformed
        // TODO add your handling code here:
        filtro = "COSMOS";
        try {
            preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_cosmosActionPerformed

    private void rb_matrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_matrizActionPerformed
        // TODO add your handling code here:
        filtro = "MATRIZ";
        try {
            preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_matrizActionPerformed

    private void rb_filialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_filialActionPerformed
        // TODO add your handling code here:
        filtro = "FILIAL";
        try {
            preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_filialActionPerformed

    private void rb_rotisseriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_rotisseriaActionPerformed
        // TODO add your handling code here:
        filtro = "ROTISSERIA";
        try {
            preencherTabela();
        } catch (IOException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_rotisseriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FuncionarioForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void preencherTabela() throws IOException {
        try {
            tf_nomePesq.grabFocus();
            FuncionarioDAO dao = new FuncionarioDAO();
            if(filtro.equals("TODOS")){
            minhaList = dao.List();
            }else if(filtro.equals("MATRIZ")){
                minhaList = dao.ListMatriz();
            }else if(filtro.equals("FILIAL")){
                minhaList = dao.ListFilial();
            }else if(filtro.equals("ROTISSERIA")){
                minhaList = dao.ListRotisseria();
            }else if(filtro.equals("COSMOS")){
                minhaList = dao.ListCosmos();
            }
            MyTableModel mtb = new MyTableModel(Funcionario.class, minhaList, tb_func);
            tb_func.setModel(mtb);
            tb_func.getColumnModel().getColumn(0).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(1).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(2).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(3).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(4).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(5).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(6).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(7).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(8).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(9).setPreferredWidth(40);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    public void preencherPesq(List<Funcionario> func) throws IOException{
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            MyTableModel mtb = new MyTableModel(Funcionario.class, minhaList, tb_func);
            tb_func.setModel(mtb);
            tb_func.getColumnModel().getColumn(0).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(1).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(2).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(3).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(4).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(5).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(6).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(7).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(8).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(9).setPreferredWidth(40);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_deletar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_sair;
    private javax.swing.JRadioButton rb_cosmos;
    private javax.swing.JRadioButton rb_filial;
    private javax.swing.JRadioButton rb_matriz;
    private javax.swing.JRadioButton rb_rotisseria;
    private javax.swing.JRadioButton rb_todos;
    private javax.swing.JTable tb_func;
    private javax.swing.JTextField tf_nomePesq;
    // End of variables declaration//GEN-END:variables
}
