/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import DAO.FuncionarioDAO;
import Entidades.Funcionario;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Airton Robson
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    String user = "";
    String senha = "";
    List<Funcionario> minhaList = new ArrayList<Funcionario>();
    String pesq = "";
    public MenuForm(String user, String senha) throws IOException {
        initComponents();
        this.user = user;
        this.senha = senha;
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_funcionarios = new javax.swing.JButton();
        jb_ferias = new javax.swing.JButton();
        jb_advertencias = new javax.swing.JButton();
        jb_atestados = new javax.swing.JButton();
        jb_suspensoes = new javax.swing.JButton();
        jb_licencaMaternidade = new javax.swing.JButton();
        jb_logout = new javax.swing.JButton();
        jb_licencaDoenca = new javax.swing.JButton();
        jb_aniv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_func = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_nomePesq = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_funcionarios = new javax.swing.JMenu();
        mi_visuFunc = new javax.swing.JMenuItem();
        mi_cadFunc = new javax.swing.JMenuItem();
        jm_opc = new javax.swing.JMenu();
        mi_novo_user = new javax.swing.JMenuItem();
        mi_altUser = new javax.swing.JMenuItem();
        mi_sairLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jb_funcionarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_funcionarios.setText("Funcionarios [F1]");
        jb_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_funcionariosActionPerformed(evt);
            }
        });
        jb_funcionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_funcionariosKeyPressed(evt);
            }
        });

        jb_ferias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_ferias.setText("Férias [F2]");
        jb_ferias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_feriasActionPerformed(evt);
            }
        });
        jb_ferias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_feriasKeyPressed(evt);
            }
        });

        jb_advertencias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_advertencias.setText("Advertências [F3]");
        jb_advertencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_advertenciasActionPerformed(evt);
            }
        });
        jb_advertencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_advertenciasKeyPressed(evt);
            }
        });

        jb_atestados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_atestados.setText("Atestados [F4]");
        jb_atestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_atestadosActionPerformed(evt);
            }
        });
        jb_atestados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_atestadosKeyPressed(evt);
            }
        });

        jb_suspensoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_suspensoes.setText("Suspensões [F5]");
        jb_suspensoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suspensoesActionPerformed(evt);
            }
        });
        jb_suspensoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_suspensoesKeyPressed(evt);
            }
        });

        jb_licencaMaternidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_licencaMaternidade.setText("Licença Maternidade [F6]");
        jb_licencaMaternidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_licencaMaternidadeActionPerformed(evt);
            }
        });
        jb_licencaMaternidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_licencaMaternidadeKeyPressed(evt);
            }
        });

        jb_logout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_logout.setText("Sair [ESC]");
        jb_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logoutActionPerformed(evt);
            }
        });
        jb_logout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_logoutKeyPressed(evt);
            }
        });

        jb_licencaDoenca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_licencaDoenca.setText("Licença por Doença [F7]");
        jb_licencaDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_licencaDoencaActionPerformed(evt);
            }
        });
        jb_licencaDoenca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_licencaDoencaKeyPressed(evt);
            }
        });

        jb_aniv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jb_aniv.setText("Aniversariantes");
        jb_aniv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_anivActionPerformed(evt);
            }
        });
        jb_aniv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_anivKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_suspensoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_licencaMaternidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_licencaDoenca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_funcionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_ferias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_advertencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_atestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jb_aniv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jb_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_ferias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_advertencias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jb_atestados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_suspensoes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jb_licencaMaternidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_licencaDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_aniv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tb_func.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_func.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_funcKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_func);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        tf_nomePesq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_nomePesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomePesqActionPerformed(evt);
            }
        });
        tf_nomePesq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_nomePesqFocusGained(evt);
            }
        });
        tf_nomePesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nomePesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nomePesqKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nomePesqKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tf_nomePesq, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(205, 205, 205))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(89, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jm_funcionarios.setText("Funcionários");

        mi_visuFunc.setText("Visualizar Funcionários");
        mi_visuFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_visuFuncActionPerformed(evt);
            }
        });
        jm_funcionarios.add(mi_visuFunc);

        mi_cadFunc.setText("Cadastrar Funcionário");
        mi_cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cadFuncActionPerformed(evt);
            }
        });
        jm_funcionarios.add(mi_cadFunc);

        jMenuBar1.add(jm_funcionarios);

        jm_opc.setText("Opções");

        mi_novo_user.setText("Novo usuário");
        mi_novo_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_novo_userActionPerformed(evt);
            }
        });
        jm_opc.add(mi_novo_user);

        mi_altUser.setText("Alterar usuario atual");
        mi_altUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_altUserActionPerformed(evt);
            }
        });
        jm_opc.add(mi_altUser);

        mi_sairLogout.setText("Sair");
        mi_sairLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_sairLogoutActionPerformed(evt);
            }
        });
        jm_opc.add(mi_sairLogout);

        jMenuBar1.add(jm_opc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(982, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(234, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        setSize(new java.awt.Dimension(1221, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_funcionariosActionPerformed
        try {
            // TODO add your handling code here:
            new FuncionarioForm().show();
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_funcionariosActionPerformed

    private void jb_feriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_feriasActionPerformed
        try {
            new FeriasForm().show();
        } catch (ParseException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_feriasActionPerformed

    private void jb_advertenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_advertenciasActionPerformed
        try {
            new AdvertenciaForm().show();
        } catch (ParseException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_advertenciasActionPerformed

    private void jb_atestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_atestadosActionPerformed
        try {
            new AtestadoForm().show();
        } catch (ParseException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_atestadosActionPerformed

    private void jb_suspensoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suspensoesActionPerformed
        try {
            // TODO add your handling code here:
            new SuspensaoForm().show();
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_suspensoesActionPerformed

    private void jb_licencaMaternidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_licencaMaternidadeActionPerformed
        // TODO add your handling code here:
        try{
        new LicencaMatForm().show();
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jb_licencaMaternidadeActionPerformed

    private void jb_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logoutActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo sair?", "Confirmação de Logout", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LoginForm().show();
            dispose();
        }
    }//GEN-LAST:event_jb_logoutActionPerformed

    private void mi_sairLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_sairLogoutActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(null, "Deseja mesmo sair?", "Confirmação de Logout", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LoginForm().show();
            dispose();
        }
    }//GEN-LAST:event_mi_sairLogoutActionPerformed

    private void mi_altUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_altUserActionPerformed
        // TODO add your handling code here:
        new AlterarUserForm(user, senha).show();
    }//GEN-LAST:event_mi_altUserActionPerformed

    private void mi_visuFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_visuFuncActionPerformed
        try {
            // TODO add your handling code here:
            new FuncionarioForm().show();
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_visuFuncActionPerformed

    private void mi_cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cadFuncActionPerformed
        // TODO add your handling code here:
        new NovoFuncForm().show();
    }//GEN-LAST:event_mi_cadFuncActionPerformed

    private void jb_licencaDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_licencaDoencaActionPerformed
        try {
            new LicencaDoeForm().show();
        } catch (ParseException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_licencaDoencaActionPerformed

    private void mi_novo_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_novo_userActionPerformed
        // TODO add your handling code here:
        new NovoUserForm().show();
    }//GEN-LAST:event_mi_novo_userActionPerformed

    private void jb_funcionariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_funcionariosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_funcionariosKeyPressed

    private void jb_feriasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_feriasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_feriasKeyPressed

    private void jb_advertenciasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_advertenciasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_advertenciasKeyPressed

    private void jb_atestadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_atestadosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_atestadosKeyPressed

    private void jb_suspensoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_suspensoesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_suspensoesKeyPressed

    private void jb_licencaMaternidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_licencaMaternidadeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_licencaMaternidadeKeyPressed

    private void jb_licencaDoencaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_licencaDoencaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_licencaDoencaKeyPressed

    private void jb_logoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_logoutKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_jb_logoutKeyPressed

    private void tb_funcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_funcKeyPressed
        // TODO add your handling code here:
       if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_tb_funcKeyPressed

    private void tf_nomePesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomePesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomePesqActionPerformed

    private void tf_nomePesqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nomePesqFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_tf_nomePesqFocusGained

    private void tf_nomePesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomePesqKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_funcionariosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_feriasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_advertenciasActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_atestadosActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_suspensoesActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_licencaMaternidadeActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F7)  
            jb_licencaDoencaActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)  
            jb_logoutActionPerformed(null);
    }//GEN-LAST:event_tf_nomePesqKeyPressed

    private void tf_nomePesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomePesqKeyReleased
        // TODO add your handling code here:
        pesq = tf_nomePesq.getText();
        String ant = "";
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            if(pesq.equals("")){
                preencherTabela();
            }else{
                minhaList =  dao.ListPesq(pesq, "TODOS");
                preencherPesq(minhaList);
                ant = pesq;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!!", "Erro", JOptionPane.ERROR_MESSAGE);
            tf_nomePesq.setText(ant);
        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tf_nomePesqKeyReleased

    private void tf_nomePesqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomePesqKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomePesqKeyTyped

    private void jb_anivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_anivActionPerformed
        // TODO add your handling code here:
        new MesAniversario().show();
    }//GEN-LAST:event_jb_anivActionPerformed

    private void jb_anivKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_anivKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_anivKeyPressed

    /**
     * @param args the command line arguments
     */
    
    public void preencherTabela() throws IOException {
        try {
            
            FuncionarioDAO dao = new FuncionarioDAO();
            minhaList = dao.List();
            MyTableModel mtb = new MyTableModel(Funcionario.class, minhaList, tb_func);
            tb_func.setModel(mtb);
            tb_func.getColumnModel().getColumn(0).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(1).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(2).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(3).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(4).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(5).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(6).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(7).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(8).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(9).setPreferredWidth(40);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    public void preencherPesq(List<Funcionario> func) throws IOException{
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            MyTableModel mtb = new MyTableModel(Funcionario.class, minhaList, tb_func);
            tb_func.setModel(mtb);
            tb_func.getColumnModel().getColumn(0).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(1).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(2).setPreferredWidth(300);
            tb_func.getColumnModel().getColumn(3).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(4).setPreferredWidth(100);
            tb_func.getColumnModel().getColumn(5).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(6).setPreferredWidth(120);
            tb_func.getColumnModel().getColumn(7).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(8).setPreferredWidth(40);
            tb_func.getColumnModel().getColumn(9).setPreferredWidth(40);
        } catch (SQLException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_advertencias;
    private javax.swing.JButton jb_aniv;
    private javax.swing.JButton jb_atestados;
    private javax.swing.JButton jb_ferias;
    private javax.swing.JButton jb_funcionarios;
    private javax.swing.JButton jb_licencaDoenca;
    private javax.swing.JButton jb_licencaMaternidade;
    private javax.swing.JButton jb_logout;
    private javax.swing.JButton jb_suspensoes;
    private javax.swing.JMenu jm_funcionarios;
    private javax.swing.JMenu jm_opc;
    private javax.swing.JMenuItem mi_altUser;
    private javax.swing.JMenuItem mi_cadFunc;
    private javax.swing.JMenuItem mi_novo_user;
    private javax.swing.JMenuItem mi_sairLogout;
    private javax.swing.JMenuItem mi_visuFunc;
    private javax.swing.JTable tb_func;
    private javax.swing.JTextField tf_nomePesq;
    // End of variables declaration//GEN-END:variables

    private Object FeriasForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
